### PR TITLE
[CODE] Add Edge support for Windows #1

### PR DESCRIPTION
**Pull request by rahulmakhija30**
# Description

Created  `class Edge(Browser)` in `browsers.py`. #1 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [x] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings 
- [x] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Comment by Samyak2** [comment]
Thanks!
 - Documentation update is not required here.
 - Need someone else to test this out and possibly add Mac support.

**Comment by Samyak2** [comment]
@rahulmakhija30 can you pull your branch again and confirm if the tests pass and check if browser history is returned for all the browsers you have?

**Comment by rahulmakhija30** [comment]
Yes, it works!

**Review by Samyak2 — CHANGES_REQUESTED** [review]
I just noticed something. The `history_SQL`, `history_file` and `profile_dir_prefixes` for Edge are the same as Chrome and Chromium.
We could avoid code duplication by re-using them as it is done in Chromium.

**Comment by rahulmakhija30** [comment]
Making `history_SQL = Chrome.history_SQL` causes the edge test on windows to fail.

error1

**Comment by Samyak2** [comment]
I looked at the SQL, the query used in `Chrome` makes more sense as it gives all visits of URLs whereas the query in `Edge` returns only the URL and its last visited timestamp.
I suggest going with `Chrome.history_SQL` and modifying the tests accordingly so that it passes (the only difference between the outputs is that 2nd entry is duplicated).

**Review by Samyak2 — APPROVED** [review]

**Comment by Samyak2** [comment]
Thanks!

**Pull request merged**
