### PR TITLE
[DOC] Document Outputs class

### LINKED ISSUE #63: [DOC] Document Outputs class
## Issue

The `generic.Outputs` class is not documented in the docs yet. Considering that this contains functions to export histories to various formats, it is an important class that has to be documented.

Also, the docstrings in that class have some formatting issues that will make the docs build fail. These have to be fixed.

## Describe the solution you'd like

 - A new file `docs/outputs.rst` which contains some brief about what this class is for and the rest should be from the docstrings.
 - Add `outputs` under `API.rst`
 - Fix docstring issues
 - Ensure the documentation looks good

## Additional context

Look at `functionality.rst` and `utils.rst` for ideas.

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
# Description

outputs docs

Fixes #63

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

# Checklist:

- [x] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [ ] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings 
- [x] Any dependent and pending changes have been merged and published
- [x] A new file docs/outputs.rst which contains some brief about what this class is for and the rest should be from the docstrings.
- [x] Add outputs under API.rst
- [ ] Fix docstring issues
- [x] Ensure the documentation looks good

### CODE REVIEW

**Comment by Samyak2** [comment]
Hi. Thank you for your PR.
I understand that it's a Work in Progress, but I have to ask you to revert the changes made to `generic.py` since the PyLint warning there has been fixed in the `feature-bookmarks` branch (using a slightly different approach).

Also, IMO the docstring in `__init__.py` should give some information about the package itself and it should link to the documentation instead of PyPI. I can open a separate issue to discuss this since the `__init__.py` is missing a few more things such as `__version__`.

The test looks good.

**Comment by rachmadaniHaryono** [comment]
> Also, IMO the docstring in __init__.py should give some information about the package itself and it should link to the documentation instead of PyPI. 

i remove the commit related to __init__.py. that commit is just quick fix from quick google search to remove the warning from linter. 

> I can open a separate issue to discuss this since the __init__.py is missing a few more things such as __version__.

i'm ok with that

> I understand that it's a Work in Progress, but I have to ask you to revert the changes made to generic.py since the PyLint warning there has been fixed in the feature-bookmarks branch (using a slightly different approach).

i just know that there is change from your branch from your comment, so i move my changes on generic.py to https://github.com/rachmadaniHaryono/browser-history/tree/feature/outputs-code-chg

this is the current result from that branch

Screen Shot 2020-10-14 at 13 31 01

**Comment by Samyak2** [comment]
@rachmadaniHaryono the `outputs-code-chg` branch looks great. Type hints are nice. (I learnt about `pytest.mark.parametrize` and `functools.partial` today, thanks!)

I just have one concern - after #76 (from `feature-bookmarks` branch) is merged you will have to rebase your changes since there is a lot of overlap between your branch and #76, some of the functions and attributes you documented have changed and new ones have been added.

**Comment by rachmadaniHaryono** [comment]
> I just have one concern - after #76 (from feature-bookmarks branch) is merged you will have to rebase your changes since there is a lot of overlap between your branch and #76, some of the functions and attributes you documented have changed and new ones have been added.

i'm ok with that. should i merge this first and rebase my branch to feature-bookmark branch?

**Comment by Samyak2** [comment]
> if yes, i can pull request from outputs-code-chg branch to feature-bookmarks branch instead of master

Yes, that would be good

**Review by Samyak2 — APPROVED** [review]

**Pull request merged**
