### PR TITLE
Updated copyright year.

### PR DESCRIPTION
**Pull request by Simba-97**
Updated the copyright year from 2020 to 2020-2021 in the documentation .
Fixed issue #170 .
Minor update.

### CODE REVIEW

**Review by Samyak2 — CHANGES_REQUESTED** [review]
From what I learnt recently, the copyright notice must include the date of first publication too ([source](https://qr.ae/pGSxnL)). So could you change the year to `2020-2021` instead?

**Comment by Simba-97** [comment]
Sure thing @Samyak2

**Comment by Simba-97** [comment]
@Samyak2 changes pushed as requested by you.

**Review by Samyak2 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
