### PR TITLE
[TESTS] Add tests for Firefox on Windows

### LINKED ISSUE #22: [TESTS] Need more tests!
# The issue

Current code [test coverage](https://codecov.io/gh/pesos/browser-history) is around ~~65%~~ 88% which may not seem too bad, but the actual situation is worse.

The tests are currently only for Firefox on Linux. 😬

# Required tests

**Browsers**

|                   | Platform | Linux | Mac | Windows |
|----------------|------------|---------|--------|---------|
| Browser     |              |           |          |         |
| Firefox       |              | ✅      |  ❌     | ❌    |
| Chrome     |              |  ❌     |  ❌     | ❌    |
| Chromium |              |  ❌     |  ❌     | ❌    |
| Safari        |              |  ⬜     |  ✅      | ⬜    |
| Edge        |              |  ⬜     |  ❌     | ✅    |
| Opera     |              |  ❌     |  ❌     | ✅    |
| Opera GX        |              |  ⬜     |  ⬜      | ✅    |
| Brave     |              |  ❌     |  ❌     | ❌    |

**CLI**

~~There are no tests are CLI currently.~~

See #65 

**generic.py**

Domain history is not tested. Refer the [codecov report](https://codecov.io/gh/pesos/browser-history/src/master/browser_history/generic.py)

# Writing Tests

Refer [this section](https://browser-history.readthedocs.io/en/latest/contributing.html#tests) in the contributing guidelines

### PR DESCRIPTION
**Pull request by ObaraEmmanuel**
# Description

Added tests for Firefox on windows platform. Created two history snapshots for two different profiles in the test_homedirs directory.
Partially fixes #22 

## Type of change

Please delete options that are not relevant.

- [x] Test (non-breaking change which adds new tests)

# Checklist:

- [x] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [x] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [x] My changes generate no new warnings 
- [x] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Review by Samyak2 — CHANGES_REQUESTED** [review]
Looks good!
Just one thing - two 5MB files will add a bit too much to the repo size. Can you try decreasing the file size somehow? (the one for Firefox on Linux is only 1.2MB)
It's fine if it cannot be reduced further but see if you can.

**Comment by ObaraEmmanuel** [comment]
I have been researching and even tried generating new snapshots but Firefox, at least on Windows, maintains and grows the places.sqlite file in 5MB chunks. They say its because of performance or something. This explains why both snapshots are exactly 5120 KB despite one of them having only one history visit. The other is also only seven history visits. I even created a new profile using their profile manager and despite having no history or bookmarks or anything its still, wait for it, 5120KB.

**Comment by ObaraEmmanuel** [comment]
Okay, I may have found a way to compact the database, standby.

**Comment by ObaraEmmanuel** [comment]
@Samyak2 I have reduced the sizes from 10MB to 2.32MB

**Comment by Samyak2** [comment]
Great! Thank you!
Can you share the way you did it? Might be useful for future contributors.

**Comment by ObaraEmmanuel** [comment]
Most if not all database tools have the _Compact database_ utility. I was using an SQLite DB browser and the procedure was as follows:

1. [Download](https://sqlitebrowser.org/) the SQLite browser 
2.  Using the browser, open the given SQLite database file. 
3. Go to `Tools > Compact database`  on the menu. 
4. Select 'main' on the dialog box then click "okay" and you are done. 
5. Close the browser and your file should be smaller. 

> This only works if the database file has unused space left by deleted records or has extra space pre-allocated as in the case of the Mozilla snapshot
>This tool works for SQLite databases so you might have to find another tool for other formats

**Review by Samyak2 — APPROVED** [review]

**Comment by Samyak2** [comment]
Thanks!
Can you do a rebase/squash so that the large files are not in the commit history/tree?

**Comment by ObaraEmmanuel** [comment]
Done, was problematic since there were newer changes in the master branch but its done

**Comment by Samyak2** [comment]
Thank you! :bow:

**Pull request merged**
