### PR TITLE
[FEATURE] Black, flake8, isort applied to codebase

### LINKED ISSUE #84: [FEATURE REQ]  Code formatter/linter + pre-commit
**Is your feature request related to a problem? Please describe.**
I usually use Black (https://github.com/psf/black) to format my code and flake8 (https://pypi.org/project/flake8/) to lint it (it covers more cases than pylint). Out of curiosity I ran both of them on current codebase and notice that it could be improved in several ways.

**Describe the solution you'd like**
If you are interested in such tools, I could apply them on code as it basically increase code readability and make it more compliant to PEP8.  
When done, I can also add a pre-commit hook to automate process when committing.

Feel free to comment should you have any thoughts on this :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by gillesigot**
# Description

I applied Black formatting, flake8 linting and also sorted import with isort (https://pypi.org/project/isort/).
I didn't want to touch logic so I just fix all findings with minor changes.

If you are ok with those changes, we can merge this and I will add those tools as pre-commit hook to automate everything.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:
- [x] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [x] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings 
- [x] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Comment by Samyak2** [comment]
Thank for the PR!

Now that `feature-bookmarks` has been merged with master, you can direct your PR to master.

**Comment by gillesigot** [comment]
Done :+1:

**Review by Samyak2 — APPROVED** [review]
Looks good to me. Thanks!

Just one thing
> Fixes #84
Since you mentioned this in the description, GitHub will close that issue after I merge this. But because #84 is also for the pre-commit hooks, I think we should leave it open.

**Comment by gillesigot** [comment]
Ok, I removed the fixes statement. Next PR is on its way :slightly_smiling_face:

**Pull request merged**
