### PR TITLE
[FEATURE REQ] Export options in CLI

### PR DESCRIPTION
**Pull request by nihal-ramaswamy**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue#6)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by sujanchegu — COMMENTED** [review]
You aren't supposed to push IDE/system related files to the repo (like .vscode/settings.json) ig.

**Comment by nihal-ramaswamy** [comment]
Oh right!! I totally forgot about that.

Regards,
Nihal Ramaswamy

**Comment by sujanchegu** [comment]
If the reason you closed the PR is that you want to make additional changes, then:

You can make changes after you have opened PR. You can just push those to your fork without closing the issue. GitHub will keep fetching commits that you push automatically until the PR is closed. 😄😄

**Comment by nihal-ramaswamy** [comment]
oh xD, ill keep that in mind xD

**Pull request closed without merging**
