### PR TITLE
[BUG FIX] History failing on windows

### LINKED ISSUE #58: [BUG] Fetching history failing on Windows
**Describe the bug**
History fetching fails almost completely on windows after commit e00280bcbaa5550b2e3b3f2fd6a9c3a2128775a4 .

**To Reproduce**
Run the following code at the terminal
```python
from browser_history import get_history
output = get_history()
```
This raises the following errors
```python
Traceback (most recent call last):
  File "C:\Users\MANU\OneDrive\Projects\browser-history\runner.py", line 5, in <module>
    main()
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\cli.py", line 55, in main
    outputs = get_history()
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\__init__.py", line 20, in get_history
    browser_output_object = browser_object.fetch()
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\generic.py", line 170, in fetch
    copied_history_path = shutil.copy2(history_path.absolute(), tmpdirname)
  File "C:\Python38\lib\shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python38\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MANU\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\History\\History'
```

**Expected behavior**
This should return history for all installed browsers but instead this error is thrown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - `browser-history`: master branch e00280bcbaa5550b2e3b3f2fd6a9c3a2128775a4
 - Python version: 3.8.0

**Additional context**
This issue can be traced back to PR #39 . The cause is probably due to hardcoding of path separators.

### PR DESCRIPTION
**Pull request by lucasace**
# Description
The previous commit though worked for Linux and MAC-OS systems broke history fetching on Windows.I fixed it by using the rglob function from pathlib. I made sure to test it on Linux and Windows systems and it works fine. MAC-OS is yet to be tested . I would like a second confirmation as well for all the OS's so as to avoid such things in the future 

Fixes #58 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [ ] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings 
- [x] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Comment by Samyak2** [comment]
This doesn't work for Chrome on Windows.
```python
from browser_history.browsers import Chrome
c = Chrome()
print(c.profiles())
```
this gives `['Default\\history', 'Guest Profile\\history']` which fails since `Default\\history\\History` is not found. 

It seems that letter casing is not preserved by `rglob` for some reason, but I couldn't find the exact reason why `rglob` doesn't return the correct output.

**Comment by lucasace** [comment]
I tried it for windows yesterday, and it worked fine for me nevertheless, I'll check for individual browsers this time,
If I cant find a solution through variations of glob, I think ill do it through the old fashioned os.walk.

**Comment by lucasace** [comment]
Could you check if it works now @Samyak2

**Comment by lucasace** [comment]
Done!

**Comment by Samyak2** [comment]
Thanks!

**Pull request merged**
