### PR TITLE
[TESTS] Add tests for Chrome & Chromium on Linux

### LINKED ISSUE #22: [TESTS] Need more tests!
# The issue

Current code [test coverage](https://codecov.io/gh/pesos/browser-history) is around ~~65%~~ 88% which may not seem too bad, but the actual situation is worse.

The tests are currently only for Firefox on Linux. 😬

# Required tests

**Browsers**

|                   | Platform | Linux | Mac | Windows |
|----------------|------------|---------|--------|---------|
| Browser     |              |           |          |         |
| Firefox       |              | ✅      |  ❌     | ❌    |
| Chrome     |              |  ❌     |  ❌     | ❌    |
| Chromium |              |  ❌     |  ❌     | ❌    |
| Safari        |              |  ⬜     |  ✅      | ⬜    |
| Edge        |              |  ⬜     |  ❌     | ✅    |
| Opera     |              |  ❌     |  ❌     | ✅    |
| Opera GX        |              |  ⬜     |  ⬜      | ✅    |
| Brave     |              |  ❌     |  ❌     | ❌    |

**CLI**

~~There are no tests are CLI currently.~~

See #65 

**generic.py**

Domain history is not tested. Refer the [codecov report](https://codecov.io/gh/pesos/browser-history/src/master/browser_history/generic.py)

# Writing Tests

Refer [this section](https://browser-history.readthedocs.io/en/latest/contributing.html#tests) in the contributing guidelines

### PR DESCRIPTION
**Pull request by gillesigot**
# Description

I added tests for Chrome & Chromium on Linux.

Fixes #22 

## Type of change

- No breaking changes, only some tests addition.

# Checklist:

- [x] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [x] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings 
- [x] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Review by Samyak2 — CHANGES_REQUESTED** [review]
The tests looks good!

I have one concern though. Four 1MB files might make the repo a bit heavy. Can you try to decrease sizes of the `History` files? (Refer [this comment](https://github.com/pesos/browser-history/pull/64#issuecomment-705135087)).

**Comment by gillesigot** [comment]
> I have one concern though. Four 1MB files might make the repo a bit heavy. Can you try to decrease sizes of the `History` files? (Refer [this comment](https://github.com/pesos/browser-history/pull/64#issuecomment-705135087)).

Thanks for pointing that out.  It's much better now (131kb).

**Review by Samyak2 — COMMENTED** [review]
Nice! The size is much better now.

I have another question.

When I compared the directory structure with my installation of chromium, there was no `.config/chromium/History` file. Instead the file for default profile is located under `.config/chromium/Default/History` and the other profiles are `Profile 1`, `Profile 2`, etc.

That is, the directory structure looks like this in my installation.
```
chromium
 -> Default -> History
 -> Profile 1 -> History
 -> Profile 2 -> History
...
```

Whereas the directory structure in your branch looks like:
```
chromium
 -> History
 -> Profile -> History
```

Can you confirm with your installations which of the directory structures chrome and chromium uses?
The tests work either way, but it's good to emulate the actual structure.

**Comment by gillesigot** [comment]
Indeed, you're right, mine is also stored under `Default`. I guess I overlooked that. I'll fix the directory structure.

**Review by Samyak2 — CHANGES_REQUESTED** [review]
After merging #76, there were a few breaking changes. One of which was that `fetch()` was changed to `fetch_history()`.
Can you rebase on master and make the required changes?
(Sorry about that :sweat_smile:)

**Comment by gillesigot** [comment]
Sure, sorry for many reviews ^^

**Review by Samyak2 — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
